---
DNS64Prefix: '1234::'
Listen:
  - proto: udp
    host: '127.0.0.1'
    port: 5300
Forwarder:
  - proto: udp
    host: '192.168.1.1'
    port: 53
DomainBlacklist: './blacklist.txt'
TunnelDetection:
  Threshold: 3
  Timespan: 10
Redirect:
  test.test:
    A: "127.0.0.1"
    AAAA: "::1"
AntiBeacon:
  Length: 10
  Threshold: 0.5
